# Generated by Django 5.2.1 on 2025-06-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='number_of_subtasks',
            new_name='number_of_tasks',
        ),
    ]
