# Generated by Django 5.2.1 on 2025-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0002_rename_number_of_subtasks_column_number_of_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='number_of_tasks',
            field=models.IntegerField(db_default=0, editable=False),
        ),
    ]
