# Generated by Django 5.2.1 on 2025-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_alter_column_number_of_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='number_of_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
