# Generated by Django 5.2.1 on 2025-06-01 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('columns', '0002_rename_number_of_subtasks_column_number_of_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=2000)),
                ('number_of_subtasks', models.IntegerField(default=0)),
                ('number_of_completed_subtasks', models.IntegerField(default=0)),
                ('status', models.CharField(default='', max_length=200)),
                ('column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columns.column')),
            ],
        ),
    ]
