# Generated by Django 5.2.1 on 2025-06-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_alter_column_number_of_tasks'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='number_of_completed_subtasks',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='number_of_subtasks',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columns.column'),
        ),
    ]
