# Generated by Django 5.2.1 on 2025-06-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_alter_column_number_of_tasks'),
        ('tasks', '0002_remove_task_column_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='columns.column'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
