# Generated by Django 5.2.1 on 2025-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number_of_completed_subtasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='number_of_subtasks',
            field=models.IntegerField(default=0),
        ),
    ]
