# Generated by Django 5.2.1 on 2025-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_number_of_completed_subtasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
